[tool.poetry]
name = "pixelmatch"
version = "0.2.2"
description = "A pixel-level image comparison library."
authors = ["Wu Haotian <whtsky@gmail.com>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/whtsky/pixelmatch-py"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
pillow = "^7.2.0"
codecov = "^2.1.10"
pytest-benchmark = "^3.2.3"
pytest-mypy = "^0.7.0"
mypy = "^0.800"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
