[tool.poetry]
name = "pixelmatch"
version = "0.1.0"
description = "A pixel-level image comparison library. Python port of https://github.com/mapbox/pixelmatch"
authors = ["Wu Haotian <whtsky@gmail.com>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.3.5"
pytest-cov = "^2.8.1"
pillow = "^7.0.0"
codecov = "^2.0.16"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
